#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const improvements = [
  {
    name: 'Update metadata with SEO-focused branding',
    file: 'app/layout.tsx',
    check: (content) => content.includes('Create Next App'),
    apply: (content) => {
      return content
        .replace('title: "Create Next App"', 'title: "SEO News Hub - Latest Search Engine Optimization News"')
        .replace('description: "Generated by create next app"', 'description: "Real-time SEO news aggregator. Stay updated with Google algorithm changes, ranking factors, and search optimization trends."');
    }
  },
  {
    name: 'Add animated gradient background',
    file: 'app/page.tsx',
    check: (content) => !content.includes('animate-gradient'),
    apply: (content) => {
      return content.replace(
        'className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 text-white"',
        'className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 text-white animate-gradient-x"'
      );
    }
  },
  {
    name: 'Add custom CSS animations',
    file: 'app/globals.css',
    check: (content) => !content.includes('@keyframes gradient-x'),
    apply: (content) => {
      return content + `

@keyframes gradient-x {
  0%, 100% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
}

.animate-gradient-x {
  background-size: 200% 200%;
  animation: gradient-x 15s ease infinite;
}

@keyframes pulse-glow {
  0%, 100% {
    box-shadow: 0 0 20px rgba(59, 130, 246, 0.3);
  }
  50% {
    box-shadow: 0 0 40px rgba(59, 130, 246, 0.6);
  }
}

.pulse-glow {
  animation: pulse-glow 3s ease-in-out infinite;
}
`;
    }
  },
  {
    name: 'Improve article card hover effects',
    file: 'app/page.tsx',
    check: (content) => !content.includes('transform-gpu'),
    apply: (content) => {
      return content.replace(
        'className="group p-6 rounded-xl bg-white/5 backdrop-blur-sm border border-white/10 hover:border-blue-500/50 hover:bg-white/10 transition-all duration-300 hover:scale-105 hover:shadow-2xl hover:shadow-blue-500/20 text-left w-full"',
        'className="group p-6 rounded-xl bg-white/5 backdrop-blur-sm border border-white/10 hover:border-blue-500/50 hover:bg-white/10 transition-all duration-300 hover:scale-105 hover:shadow-2xl hover:shadow-blue-500/20 text-left w-full transform-gpu will-change-transform"'
      );
    }
  },
  {
    name: 'Add live indicator pulse animation',
    file: 'app/page.tsx',
    check: (content) => !content.includes('pulse-glow'),
    apply: (content) => {
      return content.replace(
        'className="inline-block px-4 py-2 bg-green-500/20 rounded-full border border-green-500/30"',
        'className="inline-block px-4 py-2 bg-green-500/20 rounded-full border border-green-500/30 pulse-glow"'
      );
    }
  }
];

async function improveUI() {
  console.log('🎨 Starting UI improvements...\n');
  
  let appliedCount = 0;
  const appliedImprovements = [];
  
  for (const improvement of improvements) {
    const filePath = path.join(__dirname, '..', improvement.file);
    
    if (!fs.existsSync(filePath)) {
      console.log(`⚠️  Skipped: ${improvement.name} - File not found`);
      continue;
    }
    
    const content = fs.readFileSync(filePath, 'utf8');
    
    if (!improvement.check(content)) {
      console.log(`⏭️  Skipped: ${improvement.name} - Already applied`);
      continue;
    }
    
    const newContent = improvement.apply(content);
    fs.writeFileSync(filePath, newContent);
    
    console.log(`✅ Applied: ${improvement.name}`);
    appliedImprovements.push(improvement.name);
    appliedCount++;
  }
  
  console.log(`\n🎉 Applied ${appliedCount} improvements!`);
  
  if (appliedCount > 0) {
    return {
      success: true,
      count: appliedCount,
      improvements: appliedImprovements
    };
  } else {
    return {
      success: false,
      count: 0,
      improvements: []
    };
  }
}

if (require.main === module) {
  improveUI()
    .then(result => {
      if (result.success) {
        console.log('\n📝 Summary:');
        result.improvements.forEach((imp, i) => {
          console.log(`  ${i + 1}. ${imp}`);
        });
        process.exit(0);
      } else {
        console.log('\n✨ UI is already optimized - no improvements needed!');
        process.exit(0);
      }
    })
    .catch(err => {
      console.error('❌ Error:', err);
      process.exit(1);
    });
}

module.exports = { improveUI };
